"""Google Calendar connector.

Implements the ``IGoogleCal`` interface from the Architecture Haiku:
    * OAuth 2.0 authorize + callback flow
    * Server-side create_event (replaces the CalendarCreateEventAction mock)
    * Periodic event sync into ``cached_calendar_events`` so workflows can
      read calendar data locally without re-hitting the Google API during
      execution.

Tokens are stored per-user in ``user_connections``. Google client_id /
client_secret / redirect_uri are read from ``app.core.config.settings``;
missing credentials simply cause the connector to raise
``GoogleCalendarNotConfigured`` so the calling code can keep a mock
fallback path.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from typing import Any

from sqlalchemy.orm import Session

from app.connectors.repo import CachedCalendarEventRepository, UserConnectionRepository
from app.core.config import settings
from app.db.schema import UserConnectionORM, UserSessionORM

PROVIDER = "google_calendar"

# Calendar read + events write. "openid email" is included so we can log
# which Google account the user linked, which makes troubleshooting
# mismatched calendars ("it posts to the wrong calendar!") much easier.
DEFAULT_SCOPES: list[str] = [
    "openid",
    "https://www.googleapis.com/auth/userinfo.email",
    "https://www.googleapis.com/auth/calendar.events",
    "https://www.googleapis.com/auth/calendar.readonly",
]
_TOKEN_URI = "https://oauth2.googleapis.com/token"
_AUTH_URI = "https://accounts.google.com/o/oauth2/auth"


class GoogleCalendarError(RuntimeError):
    """Base error for this module."""


class GoogleCalendarNotConfigured(GoogleCalendarError):
    """Raised when the server is missing Google OAuth credentials."""


class GoogleCalendarNotConnected(GoogleCalendarError):
    """Raised when a specific user has no stored connection."""


@dataclass
class AuthorizeUrl:
    url: str
    state: str


def is_configured() -> bool:
    """Return True iff the server can perform OAuth exchanges at all."""
    return bool(settings.google_client_id and settings.google_client_secret)


def _require_configured() -> None:
    if not is_configured():
        raise GoogleCalendarNotConfigured(
            "GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET are not set in the backend .env"
        )


def _client_config() -> dict[str, Any]:
    return {
        "web": {
            "client_id": settings.google_client_id,
            "client_secret": settings.google_client_secret,
            "redirect_uris": [settings.google_redirect_uri],
            "auth_uri": _AUTH_URI,
            "token_uri": _TOKEN_URI,
        }
    }


def build_authorize_url(
    db: Session,
    state: str,
    scopes: list[str] | None = None,
) -> AuthorizeUrl:
    """Create the Google consent screen URL for the initial authorization.

    ``state`` should be the caller's bearer session token. We look it up in
    ``user_sessions`` and persist the PKCE ``code_verifier`` generated by
    google-auth-oauthlib on the same row so the ``/callback`` handler (a
    separate request, new ``Flow`` instance) can reproduce it when
    exchanging the auth code. Without this, google-auth-oauthlib 1.3+'s
    default ``autogenerate_code_verifier=True`` causes Google to reject
    the exchange with ``invalid_grant: Missing code verifier``.
    """
    _require_configured()
    from google_auth_oauthlib.flow import Flow  # local import — heavy dep

    session_row = db.get(UserSessionORM, state)
    if session_row is None:
        # build_authorize_url is only called from an authenticated route,
        # so the session must exist. If it doesn't, fail loudly rather
        # than silently dropping the verifier and failing later at
        # callback time with a misleading "Missing code verifier" error.
        raise GoogleCalendarError(
            f"Unknown session token passed as OAuth state={state!r}"
        )

    flow = Flow.from_client_config(
        _client_config(),
        scopes=scopes or DEFAULT_SCOPES,
        redirect_uri=settings.google_redirect_uri,
    )
    auth_url, returned_state = flow.authorization_url(
        access_type="offline",
        prompt="consent",  # force refresh_token on repeat authorizations
        include_granted_scopes="true",
        state=state,
    )
    session_row.oauth_code_verifier = flow.code_verifier
    db.add(session_row)
    db.flush()
    return AuthorizeUrl(url=auth_url, state=returned_state or state)


def exchange_code(
    db: Session,
    user_name: str,
    code: str,
    *,
    code_verifier: str | None = None,
    scopes: list[str] | None = None,
) -> UserConnectionORM:
    """Exchange an auth code for tokens and persist them for ``user_name``.

    ``code_verifier`` must match the PKCE verifier that was used to build
    the authorize URL. The router reads it from the ``user_sessions``
    row keyed by the OAuth ``state`` parameter.
    """
    _require_configured()
    from google_auth_oauthlib.flow import Flow

    flow = Flow.from_client_config(
        _client_config(),
        scopes=scopes or DEFAULT_SCOPES,
        redirect_uri=settings.google_redirect_uri,
    )
    if code_verifier:
        # Setting this on the Flow instance makes fetch_token() include
        # the code_verifier in the POST body. google-auth-oauthlib's own
        # fetch_token does not forward kwargs to oauth2session, so we have
        # to attach it to the Flow like this.
        flow.code_verifier = code_verifier
    flow.fetch_token(code=code)
    creds = flow.credentials
    return UserConnectionRepository(db).upsert(
        user_name=user_name,
        provider=PROVIDER,
        access_token=creds.token,
        refresh_token=creds.refresh_token,
        token_uri=creds.token_uri or _TOKEN_URI,
        scopes=list(creds.scopes or scopes or DEFAULT_SCOPES),
        expiry=_normalize_expiry(creds.expiry),
    )


def _normalize_expiry(expiry: datetime | None) -> datetime | None:
    if expiry is None:
        return None
    # google.oauth2.credentials.Credentials.expiry is a naive UTC datetime;
    # tag it as UTC before persistence so downstream comparisons are safe.
    if expiry.tzinfo is None:
        return expiry.replace(tzinfo=UTC)
    return expiry


def load_credentials(db: Session, user_name: str):
    """Return a refreshed google.oauth2.credentials.Credentials for the user."""
    _require_configured()
    from google.auth.transport.requests import Request as GoogleRequest
    from google.oauth2.credentials import Credentials

    row = UserConnectionRepository(db).get(user_name, PROVIDER)
    if row is None:
        raise GoogleCalendarNotConnected(
            f"User {user_name!r} has not connected a Google Calendar account"
        )

    creds = Credentials(
        token=row.access_token,
        refresh_token=row.refresh_token,
        token_uri=row.token_uri,
        client_id=settings.google_client_id,
        client_secret=settings.google_client_secret,
        scopes=list(row.scopes or DEFAULT_SCOPES),
        expiry=row.expiry.replace(tzinfo=None) if row.expiry else None,
    )

    if not creds.valid and creds.refresh_token:
        creds.refresh(GoogleRequest())
        UserConnectionRepository(db).upsert(
            user_name=user_name,
            provider=PROVIDER,
            access_token=creds.token,
            refresh_token=creds.refresh_token,
            token_uri=creds.token_uri or _TOKEN_URI,
            scopes=list(creds.scopes or DEFAULT_SCOPES),
            expiry=_normalize_expiry(creds.expiry),
        )

    return creds


def create_event(
    db: Session,
    user_name: str,
    *,
    calendar_id: str,
    title: str,
    start: str,
    end: str,
    description: str | None = None,
) -> dict[str, Any]:
    """Create an event on the user's Google calendar and return the raw response."""
    from googleapiclient.discovery import build

    creds = load_credentials(db, user_name)
    service = build("calendar", "v3", credentials=creds, cache_discovery=False)
    body: dict[str, Any] = {
        "summary": title,
        "start": _event_time(start),
        "end": _event_time(end),
    }
    if description:
        body["description"] = description
    created = (
        service.events()
        .insert(calendarId=calendar_id, body=body)
        .execute()
    )
    return created


def _event_time(value: str) -> dict[str, str]:
    """Google accepts either {date} for all-day or {dateTime, timeZone}.

    We always send dateTime. Callers may pass an ISO datetime or just a
    date — treat a bare date as midnight UTC to keep the API happy.
    """
    if "T" in value:
        return {"dateTime": value}
    return {"dateTime": f"{value}T00:00:00Z"}


def sync_events(
    db: Session,
    user_name: str,
    *,
    calendar_id: str = "primary",
    lookback_days: int = 0,
    lookahead_days: int = 30,
    max_results: int = 100,
) -> int:
    """Pull upcoming events from Google into ``cached_calendar_events``.

    Default window is "now → +30 days" — we only care about events that
    could still trigger a workflow. Keep ``lookback_days > 0`` off by
    default so the UI doesn't show yesterday's meetings as "upcoming".
    """
    from googleapiclient.discovery import build

    creds = load_credentials(db, user_name)
    service = build("calendar", "v3", credentials=creds, cache_discovery=False)
    time_min = (datetime.now(UTC) - timedelta(days=lookback_days)).isoformat()
    time_max = (datetime.now(UTC) + timedelta(days=lookahead_days)).isoformat()
    response = (
        service.events()
        .list(
            calendarId=calendar_id,
            timeMin=time_min,
            timeMax=time_max,
            singleEvents=True,
            orderBy="startTime",
            maxResults=max_results,
        )
        .execute()
    )
    repo = CachedCalendarEventRepository(db)
    saved = 0
    for item in response.get("items", []):
        provider_id = item.get("id")
        if not provider_id:
            continue
        repo.upsert(
            user_name=user_name,
            calendar_id=calendar_id,
            provider_event_id=provider_id,
            title=item.get("summary") or "(untitled)",
            description=item.get("description"),
            start=_parse_event_time(item.get("start")),
            end=_parse_event_time(item.get("end")),
            status=item.get("status"),
            html_link=item.get("htmlLink"),
            raw=item,
        )
        saved += 1
    return saved


def _parse_event_time(value: dict[str, str] | None) -> datetime | None:
    if not value:
        return None
    raw = value.get("dateTime") or value.get("date")
    if not raw:
        return None
    # All-day events come as bare YYYY-MM-DD; treat as midnight UTC so the
    # cached row is sortable alongside timed events.
    if "T" not in raw:
        raw = f"{raw}T00:00:00+00:00"
    # Google returns "...Z"; Python 3.11+'s fromisoformat handles the "Z"
    # suffix directly.
    try:
        return datetime.fromisoformat(raw.replace("Z", "+00:00"))
    except ValueError:
        return None
