"""RuleBasedStrategy — keyword/regex matching → preset workflow drafts. Zero LLM cost."""

from __future__ import annotations

import re
from datetime import UTC, datetime, timedelta

from app.suggestion.base import SuggestionResult, UserInput
from app.suggestion.strategies.base import SuggestionStrategy


def _extract_hour(text: str) -> int:
    m = re.search(r"(\d{1,2})\s*(am|pm)?", text.lower())
    if not m:
        return 9
    hour = int(m.group(1))
    suffix = m.group(2)
    if suffix == "pm" and hour < 12:
        hour += 12
    if suffix == "am" and hour == 12:
        hour = 0
    return max(0, min(23, hour))


def _extract_email(text: str) -> str:
    m = re.search(r"[\w.+-]+@[\w-]+\.[\w.-]+", text)
    return m.group(0) if m else "recipient@example.com"


def _next_iso_at_hour(hour: int) -> str:
    now = datetime.now(UTC)
    target = now.replace(hour=hour, minute=0, second=0, microsecond=0)
    if target <= now:
        target += timedelta(days=1)
    return target.isoformat()


def _build_daily_email_draft(text: str) -> dict:
    hour = _extract_hour(text)
    to = _extract_email(text)
    return {
        "name": "Daily Email",
        "description": "Generated by RuleBasedStrategy",
        "trigger": {
            "type": "time",
            "trigger_at": _next_iso_at_hour(hour),
            "timezone": "UTC",
            "recurrence": {
                "frequency": "daily",
                "interval": 1,
                "days_of_week": [],
                "cron_expression": "",
            },
        },
        "steps": [
            {
                "action_type": "send_email",
                "name": "Send Email",
                "step_order": 0,
                "to_template": to,
                "subject_template": "Daily update",
                "body_template": "Your daily summary is ready.",
            }
        ],
    }


def _build_weekly_email_draft(text: str) -> dict:
    hour = _extract_hour(text)
    to = _extract_email(text)
    return {
        "name": "Weekly Email",
        "description": "Generated by RuleBasedStrategy",
        "trigger": {
            "type": "time",
            "trigger_at": _next_iso_at_hour(hour),
            "timezone": "UTC",
            "recurrence": {
                "frequency": "weekly",
                "interval": 1,
                "days_of_week": [1],
                "cron_expression": "",
            },
        },
        "steps": [
            {
                "action_type": "send_email",
                "name": "Send Weekly Email",
                "step_order": 0,
                "to_template": to,
                "subject_template": "Weekly update",
                "body_template": "Your weekly summary is ready.",
            }
        ],
    }


def _build_webhook_to_email_draft(text: str) -> dict:
    to = _extract_email(text)
    return {
        "name": "Webhook to Email",
        "description": "Generated by RuleBasedStrategy",
        "trigger": {
            "type": "webhook",
            "path": "/incoming",
            "method": "POST",
            "secret_ref": "",
            "event_filter": "",
        },
        "steps": [
            {
                "action_type": "send_email",
                "name": "Forward to Email",
                "step_order": 0,
                "to_template": to,
                "subject_template": "Incoming webhook",
                "body_template": "Webhook payload received: {{previous_output}}",
            }
        ],
    }


def _build_interval_trigger_draft(text: str) -> dict:
    m = re.search(r"(?:every|each)\s+(\d+)\s+(minute|hour)", text.lower())
    interval = int(m.group(1)) if m else 1
    unit = m.group(2) if m else "hour"
    frequency = "minutely" if unit == "minute" else "hourly"
    return {
        "name": f"Every {interval} {unit}(s)",
        "description": "Generated by RuleBasedStrategy",
        "trigger": {
            "type": "time",
            "trigger_at": _next_iso_at_hour(datetime.now(UTC).hour),
            "timezone": "UTC",
            "recurrence": {
                "frequency": frequency,
                "interval": interval,
                "days_of_week": [],
                "cron_expression": "",
            },
        },
        "steps": [
            {
                "action_type": "http_request",
                "name": "HTTP Request",
                "step_order": 0,
                "method": "GET",
                "url_template": "https://example.com/ping",
                "headers": {},
            }
        ],
    }


def _build_http_call_draft(_text: str) -> dict:
    return {
        "name": "HTTP Call",
        "description": "Generated by RuleBasedStrategy",
        "trigger": {
            "type": "webhook",
            "path": "/trigger",
            "method": "POST",
            "secret_ref": "",
            "event_filter": "",
        },
        "steps": [
            {
                "action_type": "http_request",
                "name": "Call API",
                "step_order": 0,
                "method": "GET",
                "url_template": "https://example.com/api",
                "headers": {},
            }
        ],
    }


class RuleBasedStrategy(SuggestionStrategy):
    """Matches hard-coded regex patterns against raw_text. Returns preset drafts."""

    RULES: list[tuple[str, callable]] = [
        (r"(every day|daily).*(email|send)", _build_daily_email_draft),
        (r"(email|send).*(every day|daily)", _build_daily_email_draft),
        (r"(every week|weekly).*(email|send)", _build_weekly_email_draft),
        (r"(email|send).*(every week|weekly)", _build_weekly_email_draft),
        (r"webhook.*(forward|send).*email", _build_webhook_to_email_draft),
        (r"(every|each)\s+\d+\s+(minute|hour)", _build_interval_trigger_draft),
        (r"(call|request|fetch).*(api|url|endpoint)", _build_http_call_draft),
    ]

    async def generate_suggestion(self, user_input: UserInput) -> SuggestionResult:
        text = user_input.raw_text
        for pattern, builder in self.RULES:
            if re.search(pattern, text, re.IGNORECASE):
                draft = builder(text)
                return SuggestionResult(
                    content=(
                        f"Matched a known pattern. Created a draft workflow "
                        f"named '{draft['name']}'."
                    ),
                    workflow_draft=draft,
                    strategy_used="rule_based",
                )
        return SuggestionResult(
            content="No matching rule found for this input.",
            workflow_draft=None,
            strategy_used="rule_based",
        )
