"""TemplateStrategy — matches a template and fills parameters extracted from raw_text."""

from __future__ import annotations

import re
from datetime import UTC, datetime, timedelta

from app.suggestion.base import AnalysisResult, SuggestionResult, UserInput
from app.suggestion.strategies.base import SuggestionStrategy


def _extract_email(text: str) -> str | None:
    m = re.search(r"[\w.+-]+@[\w-]+\.[\w.-]+", text)
    return m.group(0) if m else None


def _extract_hour(text: str) -> int | None:
    m = re.search(r"(\d{1,2})\s*(am|pm)?", text.lower())
    if not m:
        return None
    hour = int(m.group(1))
    suffix = m.group(2)
    if suffix == "pm" and hour < 12:
        hour += 12
    if suffix == "am" and hour == 12:
        hour = 0
    return max(0, min(23, hour))


def _next_iso_at_hour(hour: int) -> str:
    now = datetime.now(UTC)
    target = now.replace(hour=hour, minute=0, second=0, microsecond=0)
    if target <= now:
        target += timedelta(days=1)
    return target.isoformat()


class _DailyEmailReportTemplate:
    id = "daily_email_report"

    def extract_params(self, text: str) -> dict:
        return {
            "hour": _extract_hour(text) or 9,
            "to": _extract_email(text) or "team@example.com",
        }

    def fill(self, params: dict) -> dict:
        return {
            "name": "Daily Email Report",
            "description": "Generated by TemplateStrategy",
            "trigger": {
                "type": "time",
                "trigger_at": _next_iso_at_hour(params["hour"]),
                "timezone": "UTC",
                "recurrence": {
                    "frequency": "daily",
                    "interval": 1,
                    "days_of_week": [],
                    "cron_expression": "",
                },
            },
            "steps": [
                {
                    "action_type": "send_email",
                    "name": "Send Daily Report",
                    "step_order": 0,
                    "to_template": params["to"],
                    "subject_template": "Daily Report",
                    "body_template": "Here is your daily report.",
                }
            ],
        }


class _WebhookToEmailTemplate:
    id = "webhook_to_email"

    def extract_params(self, text: str) -> dict:
        return {"to": _extract_email(text) or "team@example.com"}

    def fill(self, params: dict) -> dict:
        return {
            "name": "Webhook → Email",
            "description": "Generated by TemplateStrategy",
            "trigger": {
                "type": "webhook",
                "path": "/incoming",
                "method": "POST",
                "secret_ref": "",
                "event_filter": "",
            },
            "steps": [
                {
                    "action_type": "send_email",
                    "name": "Forward to Email",
                    "step_order": 0,
                    "to_template": params["to"],
                    "subject_template": "Incoming webhook",
                    "body_template": "Webhook payload: {{previous_output}}",
                }
            ],
        }


class _ScheduledHttpPingTemplate:
    id = "scheduled_http_ping"

    def extract_params(self, text: str) -> dict:
        m = re.search(r"https?://\S+", text)
        return {
            "url": m.group(0) if m else "https://example.com/health",
            "hour": _extract_hour(text) or 9,
        }

    def fill(self, params: dict) -> dict:
        return {
            "name": "Scheduled HTTP Ping",
            "description": "Generated by TemplateStrategy",
            "trigger": {
                "type": "time",
                "trigger_at": _next_iso_at_hour(params["hour"]),
                "timezone": "UTC",
                "recurrence": {
                    "frequency": "hourly",
                    "interval": 1,
                    "days_of_week": [],
                    "cron_expression": "",
                },
            },
            "steps": [
                {
                    "action_type": "http_request",
                    "name": "Ping Endpoint",
                    "step_order": 0,
                    "method": "GET",
                    "url_template": params["url"],
                    "headers": {},
                }
            ],
        }


class _WeeklySummaryTemplate:
    id = "weekly_summary"

    def extract_params(self, text: str) -> dict:
        return {
            "hour": _extract_hour(text) or 9,
            "to": _extract_email(text) or "team@example.com",
        }

    def fill(self, params: dict) -> dict:
        return {
            "name": "Weekly Summary",
            "description": "Generated by TemplateStrategy",
            "trigger": {
                "type": "time",
                "trigger_at": _next_iso_at_hour(params["hour"]),
                "timezone": "UTC",
                "recurrence": {
                    "frequency": "weekly",
                    "interval": 1,
                    "days_of_week": [1],
                    "cron_expression": "",
                },
            },
            "steps": [
                {
                    "action_type": "send_email",
                    "name": "Send Weekly Summary",
                    "step_order": 0,
                    "to_template": params["to"],
                    "subject_template": "Weekly Summary",
                    "body_template": "Here is your weekly summary.",
                }
            ],
        }


class TemplateStrategy(SuggestionStrategy):
    """Matches input_type to a template, extracts params, fills skeleton."""

    TEMPLATES = {
        "daily_email_report": _DailyEmailReportTemplate(),
        "webhook_to_email": _WebhookToEmailTemplate(),
        "scheduled_http_ping": _ScheduledHttpPingTemplate(),
        "weekly_summary": _WeeklySummaryTemplate(),
    }

    def __init__(self, analysis: AnalysisResult | None = None) -> None:
        self._analysis = analysis

    def set_analysis(self, analysis: AnalysisResult) -> None:
        self._analysis = analysis

    def _pick_template(self, user_input: UserInput):
        text = user_input.raw_text.lower()
        if "webhook" in text and "email" in text:
            return self.TEMPLATES["webhook_to_email"]
        if "weekly" in text or "every week" in text:
            return self.TEMPLATES["weekly_summary"]
        if ("ping" in text or "health" in text) and "http" in text:
            return self.TEMPLATES["scheduled_http_ping"]
        if "daily" in text or "every day" in text:
            return self.TEMPLATES["daily_email_report"]
        return None

    async def generate_suggestion(self, user_input: UserInput) -> SuggestionResult:
        template = self._pick_template(user_input)
        if template is None:
            return SuggestionResult(
                content="No matching template found for this input.",
                workflow_draft=None,
                strategy_used="template",
            )
        params = template.extract_params(user_input.raw_text)
        draft = template.fill(params)
        return SuggestionResult(
            content=f"Used template '{template.id}' with your parameters.",
            workflow_draft=draft,
            strategy_used="template",
        )
